# Generated by Django 3.0.4 on 2020-05-06 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('ofClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class')),
                ('ofFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetaka.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('content', models.FileField(upload_to='sourceCodes/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('ofClass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class')),
                ('ofFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetaka.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('ofClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class')),
                ('sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seltxt', models.TextField()),
                ('anchorNodeID', models.CharField(max_length=255)),
                ('anchorOffset', models.PositiveIntegerField(default=0)),
                ('focusNodeID', models.CharField(max_length=255)),
                ('focusOffset', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('scId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seltxt', models.TextField()),
                ('anchorNodeID', models.CharField(max_length=255)),
                ('anchorOffset', models.PositiveIntegerField(default=0)),
                ('focusNodeID', models.CharField(max_length=255)),
                ('focusOffset', models.PositiveIntegerField(default=0)),
                ('posX', models.PositiveIntegerField(default=0)),
                ('posY', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('lastEdited', models.DateTimeField()),
                ('scId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
