# Generated by Django 3.0.4 on 2020-04-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcecode',
            name='ofClass',
        ),
    ]
