# Generated by Django 3.0.4 on 2020-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
