# Generated by Django 3.0.4 on 2020-05-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='ofClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class'),
        ),
    ]
