# Generated by Django 3.0.4 on 2020-05-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0002_auto_20200501_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('ofClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class')),
                ('ofFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetaka.Folder')),
            ],
        ),
    ]
