# Generated by Django 3.0.4 on 2020-05-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetaka', '0002_auto_20200501_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seltxt', models.TextField()),
                ('anchorNodeID', models.CharField(max_length=255)),
                ('anchorOffset', models.PositiveIntegerField(default=0)),
                ('focusNodeID', models.CharField(max_length=255)),
                ('focusOffset', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('scId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
