# Generated by Django 3.0.4 on 2020-04-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0002_remove_sourcecode_ofclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.PositiveIntegerField(default=0)),
                ('seltxt', models.CharField(max_length=255)),
                ('anchorNodeID', models.CharField(max_length=255)),
                ('anchorOffset', models.PositiveIntegerField(default=0)),
                ('focusNodeID', models.CharField(max_length=255)),
                ('focusOffset', models.PositiveIntegerField(default=0)),
                ('posX', models.PositiveIntegerField(default=0)),
                ('posY', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('scId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
            ],
        ),
    ]
