# Generated by Django 3.0.4 on 2020-04-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='seltxt',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
