# Generated by Django 3.0.4 on 2020-04-28 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetaka', '0004_auto_20200428_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='seltxt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ofClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.Class')),
                ('scId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetaka.SourceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
