# Generated by Django 3.0.4 on 2020-04-28 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetaka', '0006_auto_20200428_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Måessage',
            new_name='Message',
        ),
    ]
