# Generated by Django 3.0.4 on 2020-04-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetaka', '0007_auto_20200428_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='scId',
            new_name='sc',
        ),
    ]
